spring.application.name=AutoLoc

# Connexion base de donnees (XAMPP - MariaDB/MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/autoloc_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Port de l'application Spring Boot (8080 par defaut ; change-le si occupe comme sur ton Tomcat XAMPP)
server.port=8090